### ISSUE TITLE
T: Mejoras

### ISSUE THREAD

**Issue by eperedo** [apprunn/dp6WebAdminGitTrack#38]
**Overview**
Mejoras en código

**Issues**
- [x] Enviar authorization header a instancia #39 
- [x] Configurar vuex #40 
- [x] Redireccionar a usuario a login si no hay token #41 
- [x] #51 Crear componente para listas Project
