### ISSUE TITLE
I: [2] (MAQ) - Listado de proyectos

### ISSUE THREAD

**Issue by AzulChic** [apprunn/dp6WebAdminGitTrack#57]
**Topic**
#54 

**Description**
- [ ] Input para búsqueda de proyectos
- [ ] Botón para agregar proyectos
- [ ] Listar proyectos, la data de cada proyecto se debe mostrar en el componente creado para la lista de proyectos
- [ ] En cada componente se debe agregar los botones para ir hacia el dashboard y hacia las actividades

**Acceptance Test**
![captura de pantalla 2018-06-12 a la s 16 17 58](https://user-images.githubusercontent.com/14998903/41318575-6c445994-6e5e-11e8-89de-edc11ed057a9.png)

**Implementation Notes**
None

**Subtasks**
N/A

**Planning Estimate**
2

**References**
None

**Latest Assets**
N/A
