### ISSUE TITLE
I: [TBD] (MAQ) - Tab de actividades sin asignar de un proyecto

### ISSUE THREAD

**Issue by AzulChic** [apprunn/dp6WebAdminGitTrack#58]
**Topic**
#54 

**Description**
- [ ] Título de proyecto
- [ ] Tabs "Sin asignar" - "Asignadas"
- [ ] Listar actividades del proyecto, en cada item de la lista se debe mostrar el ícono de un reloj y un botón para asignar la actividad (ícono de check)
- [ ] Al dar clic en el botón para asignar actividad debe enviar hacia otra pantalla

**Acceptance Test**
![captura de pantalla 2018-06-12 a la s 16 18 16](https://user-images.githubusercontent.com/14998903/41318796-21d22eda-6e5f-11e8-9495-5cc58d83a8d1.png)

**Implementation Notes**
None

**Subtasks**
N/A

**Planning Estimate**
TBD

**References**
None

**Latest Assets**
N/A
