### ISSUE TITLE
I: [TBD] (MAQ) - Asignar actividad

### ISSUE THREAD

**Issue by AzulChic** [apprunn/dp6WebAdminGitTrack#59]
**Topic**
#54 

**Description**
- [ ] Combo para seleccionar developers
- [ ] Input para mostrar y editar horas estimadas de la actividad
- [ ] El input debe estar en estado readonly o disabled, inicialmente
- [ ] A la derecha del input se debe mostrar un botón con el ícono de editar (✏️)
- [ ] Al dar clic en el botón para editar las horas estimadas, el input se debe mostrar habilitado para ingresar la data correspondiente
- [ ] Información de la actividad a asignar
- [ ] Botón "Atrás": enviará hacia la pantalla de listado de actividades sin asignar
- [ ] Botón "Asignar": enviará hacia la pantalla de listado de actividades asignadas

**Acceptance Test**
![captura de pantalla 2018-06-12 a la s 16 18 25](https://user-images.githubusercontent.com/14998903/41318916-9e1c842c-6e5f-11e8-9fed-326f4fa31f53.png)

**Implementation Notes**
None

**Subtasks**
N/A

**Planning Estimate**
TBD

**References**
#58 

**Latest Assets**
N/A
