### ISSUE TITLE
I: [TBD] (MAQ) - Tab de actividades asignadas de un proyecto

### ISSUE THREAD

**Issue by AzulChic** [apprunn/dp6WebAdminGitTrack#60]
**Topic**
#54 

**Description**
- [ ] Título de proyecto
- [ ] Tabs "Sin asignar" - "Asignadas"
- [ ] Listar actividades del proyecto, en cada item de la lista se debe mostrar, la foto del developer asignado, el ícono de un reloj y un botón para editar la asignación de la actividad (✏️)
- [ ] Al dar clic en el botón para editar la asignación de la actividad debe enviar hacia la pantalla donde se asignó la actividad en otra ruta con el título "Editar Actividad" y el botón "Asignar" debe cambiar por "Guardar" #59 

**Acceptance Test**
![captura de pantalla 2018-06-12 a la s 16 25 17](https://user-images.githubusercontent.com/14998903/41319330-0badfdc6-6e61-11e8-8e7a-f712ecf246f6.png)

**Implementation Notes**
None

**Subtasks**
N/A

**Planning Estimate**
TBD

**References**
#59 

**Latest Assets**
N/A
