### ISSUE TITLE
I: [2] (MAQ) - Maquetar pantalla de login

### ISSUE THREAD

**Issue by AzulChic** [apprunn/dp6WebAdminGitTrack#61]
**Topic**
#55 

**Description**
- [x] Imagen de barra de colores en la cabecera de la pantalla
- [x] Banner de login en toda la pantalla
- [x] Logo de gittrack arriba de los inputs de registro
- [x] Ícono de usuario (👤) e input para ingresar email de usuario
- [x] Ícono de password (🔑) e input para ingresar password de usuario
- [x] Botón para ingresar
- [x] Botón para ingresar con github
- [x] Link de "¿Olvidaste tu contraseña?"

**Acceptance Test**
![captura de pantalla 2018-06-12 a la s 16 25 32](https://user-images.githubusercontent.com/14998903/41319623-1b7423f6-6e62-11e8-8c94-fe3490830372.png)

**Implementation Notes**
None

**Subtasks**
N/A

**Planning Estimate**
2

**References**
None

**Latest Assets**
N/A
