### ISSUE TITLE
I: [1.5] (MAQ) - Listado de developers

### ISSUE THREAD

**Issue by AzulChic** [apprunn/dp6WebAdminGitTrack#62]
**Topic**
#56 

**Description**
- [ ] Título bajo el navigator
- [ ] Bajo el título un botón para agregar developer
- [ ] Al dar clic en el botón se debe mostrar otra ruta en la que se verá el formulario para crear developer
- [ ] Tabla con buscador, filtro de columnas y los siguientes datos: Nombre de developer, horas asignadas al developer, acciones y paginación
- [ ] En la columna de acciones se mostrarán los botones (👁 🗑) para ver detalles de developer y eliminarlo del listado

**Acceptance Test**
![captura de pantalla 2018-06-12 a la s 16 25 39](https://user-images.githubusercontent.com/14998903/41319856-dc194e88-6e62-11e8-9dde-461236572ae3.png)

**Implementation Notes**
None

**Subtasks**
N/A

**Planning Estimate**
1.5

**References**
None

**Latest Assets**
N/A
