### ISSUE TITLE
I: [0.5] (MAQ) - Agregar nuevo developer

### ISSUE THREAD

**Issue by AzulChic** [apprunn/dp6WebAdminGitTrack#63]
**Topic**
#56 

**Description**
- [ ] Título "Nuevo Developer"
- [ ] Input para agregar nombre
- [ ] Input para agregar correo
- [ ] Botones para cancelar y aceptar, ambos deben redireccionar hacia el listado de developers

**Acceptance Test**
![captura de pantalla 2018-06-12 a la s 16 25 48](https://user-images.githubusercontent.com/14998903/41320096-014544c2-6e64-11e8-8825-344a0ac8fdee.png)

**Implementation Notes**
None

**Subtasks**
N/A

**Planning Estimate**
0.5

**References**
None

**Latest Assets**
N/A
