### ISSUE TITLE
I: [1] (MAQ) - Listado de actividades asignadas al developer

### ISSUE THREAD

**Issue by AzulChic** [apprunn/dp6WebAdminGitTrack#64]
**Topic**
#56 

**Description**
- [ ] Nombre de developer, al mismo nivel mostrar las horas asignadas (suma de horas de cada actividad)
- [ ] Listado de actividades
- [ ] Botón "Atrás" para volver al listado de developers

**Acceptance Test**
![captura de pantalla 2018-06-12 a la s 16 26 24](https://user-images.githubusercontent.com/14998903/41320245-aa279ce8-6e64-11e8-8cb0-87ea1aece319.png)

**Implementation Notes**
None

**Subtasks**
N/A

**Planning Estimate**
1

**References**
None

**Latest Assets**
N/A
